build:
    stage: deploy
    script:
       - cp .env.example .env
       - scp -r . root@192.168.1.185:/mnt/web/www/microservices/web-meta-grabber
       - rm -rf ~/builds
       - ssh root@192.168.1.185 "chown -R nginx. /mnt/web/www/microservices/web-meta-grabber && exit"
       - ssh root@192.168.1.185 "cd /mnt/web/www/microservices/web-meta-grabber && composer install && exit"
