services:
  solemnity-meta:
    container_name: solemnity-meta
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solemnity-meta.rule=Host(`meta.solemnity.icu`)"
      - "traefik.http.routers.solemnity-meta.entrypoints=web"
      - "traefik.http.services.solemnity-meta.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy_default
